package com.saulo.timer.ui.circuit

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.runtime.mutableStateListOf
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.saulo.timer.data.CircuitDao
import com.saulo.timer.model.Circuit
import com.saulo.timer.model.Exercise
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch

class CircuitViewModel(private val circuitDao: CircuitDao) : ViewModel() {

    var circuitName by mutableStateOf("")
    var rounds by mutableStateOf("1")
    var restBetweenRounds by mutableStateOf("60")
    val exercises = mutableStateListOf<Exercise>()

    private var currentCircuitId: Int? = null

    fun clear() {
        currentCircuitId = null
        circuitName = ""
        rounds = "1"
        restBetweenRounds = "60"
        exercises.clear()
        exercises.add(Exercise("", 30, null, 15, 5))
    }

    fun loadCircuit(id: Int) {
        viewModelScope.launch {
            val circuit = circuitDao.getCircuitById(id).first()
            circuitName = circuit.name
            rounds = circuit.rounds.toString()
            restBetweenRounds = circuit.restBetweenRounds.toString()
            exercises.clear()
            exercises.addAll(circuit.exercises)
            currentCircuitId = circuit.id
        }
    }

    fun addExercise() {
        exercises.add(Exercise("", 30, null, 15, 5))
    }

    fun removeExercise(exercise: Exercise) {
        exercises.remove(exercise)
    }

    fun updateExercise(index: Int, exercise: Exercise) {
        if (index >= 0 && index < exercises.size) {
            exercises[index] = exercise
        }
    }

    suspend fun saveCircuit(): Circuit {
        val circuit = Circuit(
            id = currentCircuitId ?: 0,
            name = circuitName.ifBlank { "Circuito Sem Nome" },
            exercises = exercises.toList(),
            rounds = rounds.toIntOrNull() ?: 1,
            restBetweenRounds = restBetweenRounds.toLongOrNull() ?: 60
        )
        val newId = circuitDao.insert(circuit)
        // If it was a new circuit, update the id with the one generated by the DB
        return if (circuit.id == 0) {
            circuit.copy(id = newId.toInt())
        } else {
            circuit
        }
    }
}
